defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

sass:
  load_paths:
    - _sass
    - _sass/node_modules

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-pdf-embed